
spring:
  application:
    name: cloudgateway
  cloud:
    gateway:
      routes:
        - id: recordpage
          uri: lb://recordpage
          predicates:
            - Path=/id/**
        
            
            